### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by BD103** [mgattozzi/blog#1]
Hello! I tried viewing [Oxidizing the technical interview](https://blog.mgattozzi.dev/oxidizing-the-technical-interview/), but I received this error in Firefox:

<img width="1310" alt="firefox error" src="https://github.com/user-attachments/assets/55b67c57-a7d9-49b0-b244-cae5268d025b">

This also happens when I try connecting to <https://blog.mgattozzi.dev/> and <https://mgattozzi.dev/>.

**Comment by mgattozzi** [comment]
I had switched to using ghost's managed service rather than running my own where I had nginx redirects. I'd have to somehow setup up redirects, but haven't really spent the time to do that. The current actual url you want is -> https://www.ductile.systems/oxidizing-the-technical-interview/
